version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing serverless
      - npm install -g serverless
      - echo Installing todo API dependencies
      - cd backend
      - npm install --silent
      - echo Finished installing todo API dependencies
  build:
    commands:
      - echo Deploying todo API
      - serverless deploy
      - echo Finished deploying todo API
  post_build:
    commands:
      - echo running test
      - npm i jest
      - npm run test
      - echo Finished running test

cache:
  paths:
    - "backend/node_modules/**/*"
