service: mybackend-todo

provider:
  name: aws
  runtime: nodejs10.x
  profile: twap-dev-sls

functions:
  listTodos:
    handler: handler.listTodos
    events:
      - http:
          path: todo/list
          method: get
